spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3307/api
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
